### ISSUE TITLE
Serverless example doesn't work

### ISSUE THREAD

**Issue by ac5tin** [talentlessguy/tinyhttp#222] opened 2021-01-30 17:12 UTC
**Describe the bug**
Wrapped `app.handler` inside the `serverless-http` default export just like the example did but got an error.
```
TypeError: Cannot read property 'settings' of undefined
    at handler (...\node_modules\@tinyhttp\app\dist\index.cjs:287:37)
    at ...\node_modules\serverless-http\lib\framework\get-framework.js:9:5
    at ...\node_modules\serverless-http\serverless-http.js:19:28
```

**To Reproduce**

```javascript
exports.handler = serverless(app.handler)
```

**Versions**

* `node`: 12.x (serverless)
* `@tinyhttp/app`: 1.1.11

**Additional context**

Works if I wrap `express` app inside `serverless`

**Comment by talentlessguy** [comment] 2021-01-30 18:58
Are you trying to make AWS example work or Vercel example work?

cuz both are server less

**Comment by ac5tin** [comment] 2021-01-31 08:29
yes, the AWS example

**Comment by talentlessguy** [comment] 2021-01-31 11:35
could you please provide a reproduction repository so I can quickly set it up and spot the buggy place?

**Comment by ike18t** [comment] 2021-02-08 21:35
I ran into this issue as well.  Since @ac5tin hasn't provided a repro repo I have setup a simple example located here:
https://github.com/ike18t/tinyhttp-serverless

**Comment by talentlessguy** [comment] 2021-02-16 15:30
Found the problem!

It comes from here:

```js
 handler(req$1, res, next) {
 /* Set X-Powered-By header */
const { xPoweredBy } = this.settings;
```

for some reason `this` is undefined here

**Comment by ahmad-reza619** [comment] 2021-02-17 09:45
Hi there, i believe this has to do with where the function is called, you can refer more explanation [here](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/this%20%26%20object%20prototypes/ch2.md#implicitly-lost)

CMIIW but I think the workaround is like this
```js
exports.handler = serverless(app.handler.bind(app))
```

**Comment by talentlessguy** [comment] 2021-02-17 20:15
@ahmad-reza619 looks like your workaround works, then I will update the example and close the issue

**Closed** 2021-02-17 20:30 UTC
Labels: bug, needs reproduction
